! COMPUTE DISTANCE MATRIX USING TWO DATA MATRICES

SUBROUTINE GENERATE_DISTANCE_MATRIX1_MATRIX2(DATAPOINTS1, DATAPOINTS2, M1, M2, N, DISTMAT)

! DISTMAT = GENERATE_DISTANCE_MATRIX(DATAPOINTS)
!   
! THE ROWS OF DATAPOINTS ARE THE OBSERVATIONS X_I FROM DATAPOINTS1 AND X_J FROM DATAPOINTS2
! RETURNS DISTMAT SO THE (IJ)TH ENTRY IS NORM(X_I-X_J)^2
!
! FIRST WHITENS DATA: CENTERS AND MAKES STD DEV OF POINTS 1 
! BEFORE CALCULATIONS

! DATAPOINTS1 ARE TESTING DATA
! DATAPOINTS2 ARE TRAINING DATA
! DATAPOINTS1 IS M1 BY N
! DATAPOINTS2 IS M2 BY N

INTEGER, INTENT(IN) :: M1, M2, N
REAL*8, INTENT(INOUT), DIMENSION(M1,N) :: DATAPOINTS1
REAL*8, INTENT(INOUT), DIMENSION(M2,N) :: DATAPOINTS2
REAL*8, INTENT(OUT), DIMENSION(M1,M2) :: DISTMAT

REAL*8, DIMENSION(N) :: MEAN ! MEAN OF EVERY COLUMN OF DATAPOINTS
REAL*8, DIMENSION(N) :: SUM_SQUARE
INTEGER :: I,J,K

DISTMAT = 0.0_8

SUM_SQUARE = 0.0_8
MEAN = SUM(DATAPOINTS1, 1) / M1 

! SUBTRACT MEAN ON EVERY COLUMN OF DATAPOINTS1
DO I = 1,N
   DATAPOINTS1(:,I) = DATAPOINTS1(:,I) - MEAN(I)
END DO

DO J = 1,N
   DO I = 1,M1
      SUM_SQUARE(J) = SUM_SQUARE(J) + DATAPOINTS1(I,J)**2
   END DO
END DO

SUM_SQUARE = SQRT(SUM_SQUARE/(M1-1))
DO I = 1,N
   DATAPOINTS1(:,I) = DATAPOINTS1(:,I) / SUM_SQUARE(I)
END DO

SUM_SQUARE = 0.0_8
MEAN = SUM(DATAPOINTS2, 1) / M2

! SUBTRACT MEAN ON EVERY COLUMN OF DATAPOINTS2
DO I = 1,N
   DATAPOINTS2(:,I) = DATAPOINTS2(:,I) - MEAN(I)
END DO

DO J = 1,N
   DO I = 1,M2
      SUM_SQUARE(J) = SUM_SQUARE(J) + DATAPOINTS2(I,J)**2
   END DO
END DO

SUM_SQUARE = SQRT(SUM_SQUARE/(M2-1))
DO I = 1,N
   DATAPOINTS2(:,I) = DATAPOINTS2(:,I) / SUM_SQUARE(I)
END DO

! NOW BUILD THE DISTANCE MATRIX. DISTMAT(I,J) = ||XI-XJ||_2^2
DO I = 1,M1
   DO J = 1,M2
      DO K = 1,N
         DISTMAT(I,J) = DISTMAT(I,J) + (DATAPOINTS1(I,K)-DATAPOINTS2(J,K))**2
      END DO
   END DO
END DO
END SUBROUTINE GENERATE_DISTANCE_MATRIX1_MATRIX2
