! COMPUTE GAUSSIAN KERNEL MATRIX USING A SQUARE MATRIX

SUBROUTINE GENERATE_RBF_KERNEL(DISTMAT, M, SIGMA, A)

! A = GENERATE_RBF_KERNEL(DISTMAT SIGMA)
!
! RETURNS: 
! -A, THE SIMILARITY MATRIX, WITH A_{IJ} = EXP(-NORM(X-Y)^2/SIGMA^2)
!
! TAKES: 
! -DISTMAT, (IJ)TH ENTRY IS NORM(X_I - X_J)^2
! -SIGMA, RBF PARAMETER

! INPUT: DISTMAT: DISTANCE MATRIX
!        M: SIZE OF DISTMAT
!        SIGMA: PARAMETER IN COMPUTING RBF KERNEL

! OUTPUT: A: KERNEL MATRIX
IMPLICIT NONE 

INTEGER, INTENT(IN) :: M
REAL*8, DIMENSION(M,M), INTENT(IN) :: DISTMAT
REAL*8, INTENT(IN) :: SIGMA
REAL*8, DIMENSION(M,M), INTENT(OUT) :: A

A = EXP(-DISTMAT/(2.0*(SIGMA**2)))
END SUBROUTINE GENERATE_RBF_KERNEL
